# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-linux-windows:
    docker:
      - image: electronuserland/builder:wine
    working_directory: ~/electric-irc
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: yarn --link-duplicates --pure-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          paths:
            - node_modules
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Build The Application
          command: yarn release
  test:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - run: yarn config set prefix ~/.yarn
      - checkout
      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run:
          name: Install Greenkeeper
          command: yarn global add greenkeeper-lockfile@1
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Update Lockfile
          command: ~/.yarn/bin/greenkeeper-lockfile-update
      - save_cache:
          name: Save Yarn Package Cache
          paths:
            - node_modules
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # run tests
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - run:
          name: Report Coverage
          command: yarn report-coverage
      - run:
          name: Upload Greenkeeper Lockfile
          command: ~/.yarn/bin/greenkeeper-lockfile-upload
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build-linux-windows:
          requires:
            - test
          filters:
            branches:
              only: /master|build/
            tags:
              only: /.*/ # Force CircleCI to build on tags